name: mapbox_directions
description: This flutter package makes it easier to fetch routes from Mapbox. Currently there are only limited configurations possible.
version: 0.0.2+1
homepage: https://lab73.at
repository: https://github.com/jkronlachner/mapbox_directions


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.0
  latlng: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
